const router = require('express').Router();
const c = require('../controllers/propertyController');
const admin = require('../controllers/adminController');
const v = require('../validators/properties');
const { idParams } = require('../validators/common');
const validate = require('../middleware/validate');
const { authenticate, authorize } = require('../middleware/auth');
const { ownProperty } = require('../middleware/ownership');
router.post('/', authenticate, authorize('agent'), validate({ body: v.create }), c.create);
router.get('/search', validate({ query: v.search }), c.search);
router.get('/mine', authenticate, authorize('agent'), validate({ query: v.mine }), c.mine);
router.get('/locations', validate({ query: v.locations }), c.locations);
router.get('/city/:city', validate({ params: v.cityParams, query: v.citySearch }), c.search);
router.get('/:id', validate({ params: idParams }), c.detail);
router.put('/:id/verify', authenticate, authorize('admin'), validate({ params: idParams }), admin.verifyProperty);
router.put('/:id/status', authenticate, authorize('agent'), validate({ params: idParams, body: v.status }), ownProperty, c.status);
router.post('/:id/flag', authenticate, authorize('buyer', 'tenant'), validate({ params: idParams, body: v.flag }), c.flag);
router.put('/:id', authenticate, authorize('agent'), validate({ params: idParams, body: v.update }), ownProperty, c.update);
router.delete('/:id', authenticate, authorize('agent'), validate({ params: idParams }), ownProperty, c.remove);
module.exports = router;
